### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by serdardundar** [messenger4j/messenger4j-spring-boot-quickstart-template#13]
When I sent a webhook test from my Developer Facebook account, handle callback fails. Sent data is a json as:

{"entry": [{"time": 1506330278, "changes": [{"field": "message_sends", "value": {"to": {"data": [{"email": "bobbert@tehfacebook.com", "id": 20061985, "name": "Bobbert Cruz"}]}, "message": "I'm changing jobs for the next 4+ years. Wanna be CEO?", "from": {"email": "zuck@tehfacebook.com", "id": 44444444, "name": "Lizard Zuckerman"}, "id": "mid.86753098675309:uuddlrlrbas"}}], "id": "0", "uid": "0"}], "object": "user"}

but in handleCallback method, an exception is thrown. Console log is:

java.lang.IllegalArgumentException: 'object' property has to be 'page'. Make sure this is a page subscription
	at com.github.messenger4j.receive.MessengerReceiveClientImpl.processCallbackPayload(MessengerReceiveClientImpl.java:138) ~[messenger4j-0.8.0.jar:na]
	at com.fourplay.handler.MessengerPlatformCallbackHandler.handleCallback(MessengerPlatformCallbackHandler.java:160) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]

Can you help me please?

Thanks for your API.

Regards.

**Comment by maxgrabenhorst** [comment]
Hi, your provided JSON data has the wrong format.
Try to setup your bot / webhook as described in the README and use a Messenger Client (web/mobile) to do your testing.

Regards

**Comment by maxgrabenhorst** [comment]
I close this issue. If you still have problems please reopen.
