### ISSUE TITLE
The access token could not decrypted

### ISSUE THREAD

**Issue by zdcsoul** [messenger4j/messenger4j-spring-boot-quickstart-template#4]
2017-05-13T16:03:14.633252+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633253+00:00 app[web.1]:    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:14.633254+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:14.633254+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633255+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633256+00:00 app[web.1]:    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633256+00:00 app[web.1]:    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633257+00:00 app[web.1]:    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633258+00:00 app[web.1]:    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633258+00:00 app[web.1]:    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633259+00:00 app[web.1]:    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633260+00:00 app[web.1]:    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633264+00:00 app[web.1]:    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633265+00:00 app[web.1]:    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633266+00:00 app[web.1]:    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633267+00:00 app[web.1]:    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633267+00:00 app[web.1]:    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633268+00:00 app[web.1]:    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633269+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:14.633270+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:14.633270+00:00 app[web.1]:    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:14.633271+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:14.633272+00:00 app[web.1]: 
2017-05-13T16:03:14.634105+00:00 heroku[router]: at=info method=POST path="/callback" host=msg4j.herokuapp.com request_id=37dd2804-0ee5-494a-98fb-81aa2ef9e0d1 fwd="66.220.152.176" dyno=web.1 connect=0ms service=62ms status=200 bytes=92 protocol=https
2017-05-13T16:03:53.918259+00:00 heroku[router]: at=info method=POST path="/callback" host=msg4j.herokuapp.com request_id=8f16838b-020e-4a11-8902-2e19db0efaea fwd="66.220.152.131" dyno=web.1 connect=0ms service=64ms status=200 bytes=92 protocol=https
2017-05-13T16:03:53.862439+00:00 app[web.1]: 2017-05-13 16:03:53.862  INFO 4 --- [o-16700-exec-10] g.m.q.b.MessengerPlatformCallbackHandler : Received message 'mid.$cAAHWcdxHpQFiM9KUGVcAo8Kp3Mdp' with text 'kkk' from user '1394892580557015' at 'Sat May 13 16:03:53 UTC 2017'
2017-05-13T16:03:53.916881+00:00 app[web.1]: 2017-05-13 16:03:53.916 ERROR 4 --- [o-16700-exec-10] g.m.q.b.MessengerPlatformCallbackHandler : Message could not be sent. An unexpected error occurred.
2017-05-13T16:03:53.916884+00:00 app[web.1]: 
2017-05-13T16:03:53.916885+00:00 app[web.1]: com.github.messenger4j.exceptions.MessengerApiException: The access token could not be decrypted
2017-05-13T16:03:53.916889+00:00 app[web.1]:    at com.github.messenger4j.common.MessengerRestClientAbstract.doRequest(MessengerRestClientAbstract.java:40) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916888+00:00 app[web.1]:    at com.github.messenger4j.exceptions.MessengerApiException.fromJson(MessengerApiException.java:38) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916890+00:00 app[web.1]:    at com.github.messenger4j.send.MessengerSendClientImpl.sendPayload(MessengerSendClientImpl.java:300) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916890+00:00 app[web.1]:    at com.github.messenger4j.send.MessengerSendClientImpl.sendTextMessage(MessengerSendClientImpl.java:108) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916891+00:00 app[web.1]:    at com.github.messenger4j.quickstart.boot.MessengerPlatformCallbackHandler.sendTextMessage(MessengerPlatformCallbackHandler.java:493) [classes!/:1.0.2]
2017-05-13T16:03:53.916892+00:00 app[web.1]:    at com.github.messenger4j.quickstart.boot.MessengerPlatformCallbackHandler.lambda$newTextMessageEventHandler$0(MessengerPlatformCallbackHandler.java:207) [classes!/:1.0.2]
2017-05-13T16:03:53.916893+00:00 app[web.1]:    at com.github.messenger4j.receive.callers.EventHandlerCaller.callHandlerIfResponsibleForEvent(EventHandlerCaller.java:76) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916894+00:00 app[web.1]:    at com.github.messenger4j.receive.MessengerReceiveClientImpl.processMessagingEvent(MessengerReceiveClientImpl.java:158) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916894+00:00 app[web.1]:    at com.github.messenger4j.receive.MessengerReceiveClientImpl.processEntry(MessengerReceiveClientImpl.java:151) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916895+00:00 app[web.1]:    at com.github.messenger4j.receive.MessengerReceiveClientImpl.processCallbackPayload(MessengerReceiveClientImpl.java:144) ~[messenger4j-0.8.0.jar!/:na]
2017-05-13T16:03:53.916896+00:00 app[web.1]:    at com.github.messenger4j.quickstart.boot.MessengerPlatformCallbackHandler.handleCallback(MessengerPlatformCallbackHandler.java:129) [classes!/:1.0.2]
2017-05-13T16:03:53.916897+00:00 app[web.1]:    at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[na:na]
2017-05-13T16:03:53.916897+00:00 app[web.1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:53.916898+00:00 app[web.1]:    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:53.916899+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916900+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916901+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916902+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916902+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916903+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916904+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916905+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916905+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916906+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916907+00:00 app[web.1]:    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916908+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916912+00:00 app[web.1]:    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916913+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916913+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916914+00:00 app[web.1]:    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916915+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916916+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916916+00:00 app[web.1]:    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916917+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916918+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916919+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916921+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916920+00:00 app[web.1]:    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916921+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916922+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916923+00:00 app[web.1]:    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916923+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916924+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916925+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916926+00:00 app[web.1]:    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916926+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2017-05-13T16:03:53.916927+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916928+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916928+00:00 app[web.1]:    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916929+00:00 app[web.1]:    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916930+00:00 app[web.1]:    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916950+00:00 app[web.1]:    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916951+00:00 app[web.1]:    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916951+00:00 app[web.1]:    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916952+00:00 app[web.1]:    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916953+00:00 app[web.1]:    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916956+00:00 app[web.1]:    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916957+00:00 app[web.1]:    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916957+00:00 app[web.1]:    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916958+00:00 app[web.1]:    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916958+00:00 app[web.1]:    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916959+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:53.916960+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:53.916961+00:00 app[web.1]:    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
2017-05-13T16:03:53.916961+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121-heroku16]
2017-05-13T16:03:53.916962+00:00 app[web.1]: 
2017-05-13T16:37:45.411142+00:00 heroku[web.1]: Idling
2017-05-13T16:37:45.411759+00:00 heroku[web.1]: State changed from up to down
2017-05-13T16:37:46.006590+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2017-05-13T16:37:46.018526+00:00 app[web.1]: 2017-05-13 16:37:46.017  INFO 4 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2328c243: startup date [Sat May 13 15:00:03 UTC 2017]; root of context hierarchy
2017-05-13T16:37:46.025066+00:00 app[web.1]: 2017-05-13 16:37:46.023  INFO 4 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-05-13T16:37:46.286005+00:00 heroku[web.1]: Process exited with status 143

**Comment by maxgrabenhorst** [comment]
Your configured PAGE_ACCESS_TOKEN is wrong / invalid. Please make sure that you copy the full token and configure it as described in the step-by-step guide (README). If you cannot solve the problem please reopen.
